# Generated by Django 5.2.8 on 2025-12-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('credit_score', models.IntegerField(default=0)),
                ('avg_monthly_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_monthly_orders', models.IntegerField()),
                ('business_stability_score', models.IntegerField(default=0)),
                ('payment_history_score', models.IntegerField(default=0)),
                ('suggested_tenure_months', models.IntegerField()),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligibility_reason', models.TextField()),
                ('recommendation_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Suggestion',
                'verbose_name_plural': 'Loan Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_inquiries', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.loansuggestion')),
            ],
            options={
                'verbose_name': 'Loan Inquiry',
                'verbose_name_plural': 'Loan Inquiries',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
