# Generated by Django 5.2.8 on 2025-12-02 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Banking'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='products.product')),
                ('retailer', models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Sale',
                'verbose_name_plural': 'Daily Sales',
                'db_table': 'daily_sales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['retailer', 'sale_date'], name='daily_sales_retaile_0e91dd_idx'), models.Index(fields=['product', 'sale_date'], name='daily_sales_product_fc5138_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('total_sales', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Sales Summary',
                'verbose_name_plural': 'Daily Sales Summaries',
                'db_table': 'daily_sales_summary',
                'ordering': ['-sale_date'],
                'unique_together': {('retailer', 'sale_date')},
            },
        ),
    ]
