# Generated by Django 5.2.8 on 2025-12-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='dailysale',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='dailysale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='dailysalessummary',
            name='total_card',
        ),
        migrations.RemoveField(
            model_name='dailysalessummary',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='dailysalessummary',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='dailysalessummary',
            name='total_mobile',
        ),
    ]
