# Generated by Django 5.2.8 on 2025-12-02 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_dailysale_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
