# Generated by Django 5.2.8 on 2025-11-25 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField()),
                ('business_category', models.CharField(choices=[('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('cosmetics', 'Cosmetics'), ('electronics', 'Electronics'), ('general_store', 'General Store'), ('online', 'Online')], max_length=50)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retailer Profile',
                'verbose_name_plural': 'Retailer Profiles',
                'db_table': 'retailer_profiles',
            },
        ),
    ]
